### ISSUE TITLE
리펙토링된 프로젝트의 오류 발견하여 수정하기

### ISSUE THREAD

**Issue by woojae9488** [LeeHyunSeong/chatting#2]
- 오류 발견 후 수정하여 실행 결과에 대해 코멘트 추가할 것
- 스크린샷 필수

**Comment by LeeHyunSeong** [comment]
refactor 이후

2021.02.17
 - 롬복 미설치로 인한 실행 오류 수정.
 - 방 생성 시 만들어지지 않는 오류 수정.
2020.02.18
 - 서버가 각 방의 정보를 보내지 않는 오류 수정.
 - 채팅방에서 채팅 시 웹 소켓이 중지되는 오류 수정.
 - 채팅 프로그램 정상 작동 확인.
2020.02.20
 - MainController 코드 Restful하게 수정 및 매개변수 타입 및 구성 수정.
 - SocketHandler에서 객체 정보 전달하는 부분 수정.
 - RequestMapping부분에서 ModelAndView 삭제.
 - chat.html 및 room.html 자바스크립트 변수명 수정 및 코드 내용 효율적으로 수정

**Comment by LeeHyunSeong** [comment]
실행 결과 스크린샷
![채팅방](https://user-images.githubusercontent.com/61196115/108585582-8fcb1980-738c-11eb-8141-baa6755d4d22.PNG)
채팅방 목록(room.html)
![채팅화면](https://user-images.githubusercontent.com/61196115/108585583-90fc4680-738c-11eb-9d89-d9d8b2d93f09.PNG)
채팅창 화면(chat.html)
