### ISSUE TITLE
채팅 프로그램 DB ERD 설계

### ISSUE THREAD

**Issue by LeeHyunSeong** [LeeHyunSeong/chatting#7]
~21-02-21~
![11](https://user-images.githubusercontent.com/61196115/108628147-95178980-749c-11eb-919a-ea0fa7be7e69.PNG)
1차 설계 
  - 유저는 자신의 닉네임을 설정함으로써 자신을 만들 수 있다.
  - 유저는 자신의 닉네임을 바꿀 수 있다.
  - 유저는 채팅방을 만들 수 있다.
  - 유저는 채팅목록에 있는 채팅방에 참여할 수 있다.
  - 유저는 자신이 소속된 채팅방의 목록을 확인할 수 있다.
  - 유저는 채팅방에서 채팅을 할 수 있다.
  - 유저는 채팅방을 나갈 수 있으며, 그 경우 채팅방은 유저의 목록에서 삭제된다.
  - 모든 유저가 채팅방을 나가면 채팅방은 삭제된다.

21-02-22
![ERD](https://user-images.githubusercontent.com/61196115/108695325-7f10d400-7543-11eb-9208-9fb93b62de8d.PNG)
2차 설계
  - 네이밍 수정.
  - 채팅 테이블에서 채팅 시간 순 나열을 위해 생성 시간 추가.
  - 유저 테이블에서 유저 인증을 위한 패스워드 추가.
  - 채팅방 테이블에서 최근 활동 순 나열을 위해 마지막 활동 시간 추가.
  - 친구 기능을 위해 유저 테이블간의 관계 추가.

**Comment by LeeHyunSeong** [comment]
3차 설계
![ERD](https://user-images.githubusercontent.com/61196115/108723423-95308b80-7567-11eb-91f3-ae171b7de99a.PNG)

**DB 설계**
chat_user
  - 채팅을 이용하는 사용자를 관리하는 테이블
  - id(BIGINT) : 고유 번호
  - email(VARCHAR(45)) : 로그인 시 사용하는 email
  - password(VARCHAR(45)) : 로그인 시 사용하는 비밀번호
  - name(VARCHAR(10)) : 채팅에서 사용할 이름
  - second_pw(TINYINT(4)) : 2차 비밀번호

chat_friend
  - 유저의 친구를 관리하는 테이블
  - char_user_id_self(BIGINT) : 사용자 고유번호
  - char_user_id_others(BIGINT) : 친구 사용자 고유번호
  - is_hidden(BOOLEAN) : 숨긴 친구인가
  - is_block(BOOLEAN) : 차단 친구인가
  - is_each_other(BOOLEAN) : 상대도 친구인가 -> 아닐 시 상대 추천 친구에 사용자 표시

chat_room
  - 생성된 채팅방을 관리하는 테이블
  - id(BIGINT) : 채팅방 고유번호
  - name(VARCHAR(45)) : 채팅방 이름 - 모두에게 동일하게 보이는 이름 = 채팅방 초대 시 초기값

chat_member
  - 채팅방 구성 멤버를 관리하는 테이블
  - char_user_id(BIGINT) : 구성원 사용자 고유번호
  - char_room_id(BIGINT) : 소속 채팅방 고유번호
  - is_bookmark(BOOLEAN) : 즐겨찾기인가
  - is_fix(BOOLEAN) : 상단고정인가
  - is_alarm(BOOLEAN) : 안읽은 메시지를 표시하는가
  - room_nickname(VARCHAR(45)) : 유저별 채팅방 이름 개인 설정

chat_message
  - 채팅을 관리하는 테이블
  - id(BIGINT) : 고유 번호
  - content(VARCHAR(45)) : 채팅 내용
  - created_time(DATATIME) : 채팅 전송 시간
  - type(BIT(2)) : 데이터 타입 = 메시지, 사진, 동영상, 이모티콘

chat_chatting
  - 각 채팅방의 메시지를 관리하는 테이블
  - chat_room_id(BIGINT) : 메시지가 소속된 채팅방 고유번호
  - chat_message_id(BIGINT) : 메시지 고유번호
  - is_notice(BOOLEAN) : 공지로 지정된 메시지인가

chat_log
  - 각 채팅을 확인할 수 있는 사용자의 채팅 상태를 관리하는 테이블
  - chat_user_id(BIGINT) : 채팅이 소속된 채팅방에 소속된 사용자 고유번호
  - chat_message_id(BIGINT) : 채팅 고유번호
  - is_delete(BOOLEAN) : 사용자가 해당 채팅방에서 해당 채팅을 삭제했는가(해당 유저만 안보임)
  - is_check(BOOLEAN) : 사용자가 해당 채팅을 확인했는가

chat_vote
  - 채팅방에서 이루어진 투표의 제목과 결과를 관리하는 테이블
  - id(BIGINT) : 고유번호
  - title(VARCHAR(45)) : 투표 제목
  - result(VARCHAR(45)) : 투표 결과

chat_research
  - 어느 투표가 어느 채팅방에서 이뤄졌는지 관리하는 테이블
  - chat_room_id(BIGINT) : 투표가 이뤄진 채팅방 고유번호
  - chat_vote_id(BIGINT) : 해당 채팅방에서 이뤄진 투표 고유번호

**동작**
가입 및 로그인
  - 회원가입 -> 이메일과 비밀번호, 이름 입력
  - 로그인 -> 입력한 이메일과 비밀번호 확인
  - 이중비번 -> 처음에 null -> null일 땐 2중 번호 x, 4자리 번호로 설정 시 로그인 시 확인

친구 관리
  - 친구목록 -> 자신의 친구 목록 확인 가능, 친구 추가, 기존 친구 숨김, 차단, 가능, 1대1 채팅 만들기, 단톡 만들기 가능
  - 친구추가 -> 이름이나 이메일을 통해 친구 추가
  - 추천친구 -> 자신을 친구 추가한 친구 목록
  - 숨김친구 -> 목록에서 안보이도록 설정
  - 차단친구 -> 목록에서 안보이고, 채팅요청 시 차단
 
채팅방 만들기
  - 1대1 채팅 만들기 -> 원하는 상대와 1대1 채팅 만들기 가능 -> 1대1 채팅에서만의 기능
  - 단톡방 만들기 -> 채팅방 이름, 초대 멤버 선택 후 만들기 -> 자동 초대 후 모두에게 해당 방 이름으로 단톡 생성
  - 초대하기 -> 채팅방에 없는 친구 초대 가능

채팅방 목록 관리
  - 채팅목록 -> 사용자가 소속된 채팅방 목록 제공
  - 즐겨찾기 -> 사용자가 자주 이용하는 채팅방 표시
  - 상단고정 -> 최신 활동 순으로 정렬 -> 상단 고정된 채팅방은 맨 위에 배치
  - 알림끄기 -> 알람을 끈 채팅방은 안읽은 메시지 표시 off

채팅방 내 기능
  - 채팅방 이름 바꾸기 -> 채팅방의 이름을 변경 -> 나에게만 적용
  - 채팅보내기 -> 입력한 채팅 보내기
  - 사진보내기 -> 선택한 사진 전송
  - 동영상보내기 -> 선택한 동영상 전송
  - 이모티콘보내기 -> 선택한 이모티콘 전송
  - 과거기록보기 -> 일정량의 채팅을 보여주고 특정 동작 시 그 이전의 채팅 확인
  - 단어로 찾기 -> 지금까지 채팅 중 단어로 찾기
  - 답장하기 -> 특정 메시지 선택 후 해당 답에 답장
  - 공지하기 -> 특정 메시지를 공지로 등록
  - 투표하기 -> 투표 기능 제공
  - 채팅방나가기 -> 채팅방에서 나감 -> 기존 모든 기록 삭제 -> 계속 있는 멤버는 그대로
  - 채팅보내기 취소 -> 특정 시간 내 삭제 시 채팅 기록 삭제
  - 채팅개별삭제 -> 자신의 화면에서만 원하는 채팅 삭제
  - 채팅기록삭제 -> 자신의 화면에서만 모든 채팅 삭제
  - 읽은 멤버 수 -> 메시지 전송 시 읽은 멤버 수 확인 처음 n-1(보낸사람 제외) 읽을 수록 -1
  - 채팅 시간 -> 메시지 전송 시간 표시

채팅방 나가기 후 초대
  - 단톡 나갔다가 다시 초대 -> 해당 사용자의 채팅 로그만 삭제
  - 1대1 채팅 나갔다가 다시 초대 -> 해당 사용자의 채팅 로그만 삭제

**Comment by woojae9488** [comment]
## 문제점 분석
#### DB 설계
- chat_ prefix를 굳이 앞에 다 붙일 필요가 있을까?
    - chat DB schema 안에 chat_ prefix가 없는 테이블로 구성하자.
#### chat_friend 테이블
- user_id_self, user_id_others면 other이 아니므로 친구 리스트가 others에 들어가는가? 
    - 해당 칼럼에 친구 id가 들어갈 거면 user_id, friend_id가 훨씬 직관적이다.
    - 변수명 구성 시 직관적으로 설계하자.
- is_hidden, is_block, is_each_other이 있다면, 나중에 즐겨찾기가 추가된다면 is_best_friend라는 칼럼을 넣은 것인가?
    - type string으로 관리하자.. type은 자바 어플리케이션 레벨에서 enum 클래스로 관리하면 편하다.
    - 대부분은 이렇게 한다...
    - hidden, block, each_other, best_friend라는 타입들은 한 번에 2개 이상이 선택되지 못하는 값들이니 type으로 관리하는게 훨~씬 낫다.
- 대부분 로그 관리를 위해 created_at(created_time)은 되도록이면 테이블에 추가해주는 것이 좋다.
#### chat_user 테이블
- 카톡을 배경으로 했는지 아니면 다른 메시지 어플을 배경으로 했는지는 모르겠지만, 대부분의 메시지 어플은 프로필 이미지를 유지하고 있는 것으로 아는데.. 프로필 이미지가 없다니..
- second_pw는 어떤 값을 가지고 있는지 모르겠고, 만약 2차 비번을 사용한다면 2차 비번 사용 여부를 따로 칼럼으로 가지고 있어야 하는 거 아닌가?
- 그리고 name이라는 칼럼은 내가 생각하기에 유저의 진짜 이름을 의미하는 것 같은데 그렇다면 유저의 로그인 시 아이디는 어디 있는거지? 만약 유저의 로그인 시 아이디가 name이라면 유저의 진짜 이름은 어디 있는 거지?
    - 카카오톡의 로그인 시 아이디와 실제 보여지는 이름(nickname)은 다르다.
#### chat_log 테이블
- 왜 존재하는 지 모르겠음. chat_message와 다대일 관계인 것도 이해가 안가고, chat_message와 일대일 관계가 될 거 같은데 왜 분리시킨 거지? 정규화 관점에서도 이해가 안 가는 테이블
#### chat_message 테이블
- 메시지의 콘텐츠가 VARCHAR(45)면... 45자 이상의 메시지 입력시에는 전체 입력이 안되고 짤리는데 고려한 부분인지...
- created_time이 DATE면 ms 값이 아니라 2021-02-23까지만 들어갈 거 같은데 의도한 바인지... (시간 순에 따른 정렬 불가)
- type이 무엇을 의미하는 거지? BIT(2)라면 4가지의 상태를 표현하려고 한 거 같은데 뭘 하려는 건지 상상이 안 감.
#### chat_member 테이블
- 마찬가지로 is_ prefix 칼럼들 존재 여부를 모르겠음.
- joined_at(joined_time) 같은 로그 관리나 채팅방 참여 관리 시 필요한 정보가 없음.
- room_nickname이라기 보다는 room_alias 이런 게 더 의미가 맞을 거 같음.
#### chat_room 테이블
- chat_member 마다 룸 이름을 따로 저장할 거면 뭐하러 name 칼럼을 따로 가지고 있는지 모르겠음.
- chat_chatting을 따로 분리한 이유도 모르겠고, 해당 테이블과 일대다 관계인 것도 이해 안 감.
- 채팅방 생성 시간도 없음.
#### chat_chatting
- is_notice는 뭘 의미하는 건지 모르겠음.
    - 공지 메시지를 의미하는 거면 message 테이블에 들어 있어야 하는 거 아닌가?
#### chat_research, chat_vote 테이블
- 우선 지금 넣을 필요가 없는 테이블들 같다. 위에 테이블 구성부터 탄탄히 하고 투표 서비스를 도입하고 싶다면 그 때 설계해도 늦지 않는다.

**Comment by LeeHyunSeong** [comment]
4차 설계
![ERD](https://user-images.githubusercontent.com/61196115/108985247-30467400-76d4-11eb-846c-8b4d32519701.PNG)
피드백 참고 후 수정
  - relation : 친구와의 관계(숨김, 차단, 즐겨찾기, 맞팔 여부 등)
  - room_setting : 유저의 해당 채팅방 설정(즐겨찾기, 상단 고정, 알림 on/off 등)

**Comment by woojae9488** [comment]
## 문제점 분석 2
#### 변경이 필요한 사항
- chat_ prefix를 제거하자고 햇는데 반영이 안되어 있음.
- 모든 테이블에는 id PK가 있는 편이 좋을 거 같음.
- chat_member의 setting은 chat_member에 있는 게 아니라, 유저마다 setting 테이블이 따로 있어야 할 거 같음.
- second_pw를 왜 쓰는 건지 잘 모르겟음. 오버스펙인 거 같음.
- chat_message는 누가 보냈는지는 상관 안해도 되는 건가?
- chat_message의 is_notice 같은 것도 type으로 빼는 게 더 좋음 => 텍스트, 이모티콘, 노티스 등
- chat_room의 마지막 메시지를 찾으려면(카톡의 채팅 목록 창에서는 마지막 메시지가 뜬다.) 메시지 테이블에서 해당 chat_room의 메시지 다 뽑아와서 정렬한 다음에 찾아야겟네

#### 주관적 판단
- relation_type 같은 걸로 표현하자. 읽었을 때 해당 값이 enum값인지 인지가 되면 좋겠다.
- checked_num는 왜 있는거지? 읽은 횟수인가? 그렇다면 한 명이 오랫동안 안 들어왓다가 메시지 읽으면 몇 백개의 메시지 데이터가 갱신될 텐데 거기에 대한 오버헤드는 고려했는지?
- updated_time이 필요한 것들은 생각해보고 추가하자.
- user 테이블의 name -> username, image -> profile_image

**수정 사항에 대해 피드백이 오면 되도록이면 꼼꼼히 반영하자. 반영 안 할거면 코멘트라도 적자.**
**위의 수정 사항 이외에도 좀 더 고려해서 설계하도록. 그리고 웹 소켓 관련 지식 정리하라고 했는데 진전이 없는 것 같다.**

**Comment by LeeHyunSeong** [comment]
5차 설계
![ERD](https://user-images.githubusercontent.com/61196115/109144847-10cb4c00-77a5-11eb-823c-1e67729aa271.PNG)
  - id PK 추가
  - user 테이블 네이밍 변경
  - 테이블 명에 prefix 삭제
  - member 테이블의 setting_meta 수정
  - member 테이블의 last_entrance_time 추가 -> 읽은 수 체크 및 안 읽은 메시지 체크
  - room 테이블의 updated_time 추가 -> for 채팅방 정렬
  - message 테이블에 type 추가 -> text, emoticon, notice 지정

**Comment by LeeHyunSeong** [comment]
최종 설계
![ERD](https://user-images.githubusercontent.com/61196115/109156337-0d8b8c80-77b4-11eb-819d-cf86f3ad4d13.PNG)
  - room 테이블에 updated_time 제거
  - room 테이블에 last_msg_id 추가 -> 마지막 채팅 id
